### ISSUE TITLE
1.8-pre broken

### ISSUE THREAD

**Issue by kraigu** [CommunityHoneyNetwork/rdphoney#18]
Is this a known issue? If not, it is now. My 1.7 rdphoney pot is just fine, but as reported on mailing list originally 4 June by SW and confirmed by myself, a checkout of 1.8 pre fails on startup:

rdphoney_1  | [CRIT] - No deploy key found

despite a deploy key very clearly being present.

**Comment by JesseBowling** [comment]
Can you confirm what your docker-compose.yml file has for mapping the rdphoney.sysconfig file into the container?

I believe the documentation (and the 1.7 deploy script) has a holdover error for this location. It *should* read:

`- ./rdphoney.sysconfig:/etc/default/rdphoney:z`

I’m working through getting this reflected in the documentation and various scripts…For now you can update the line in the deployment script and re-deploy, or simply fix the line in the sysconfig file. I’d recommend removing the existing instance of the rdphoney container and re-upping it to be sure the change in sysconfig file is reflected.

docker-compose stop rdphoney && docker-compose rm -f rdphoney && docker-compose up -d rdphoney

**Comment by JesseBowling** [comment]
This should be resolved with a docker-compose pull for 1.8-pre rdphoney images.
