### ISSUE TITLE
Fails to find rdphoney.json file

### ISSUE THREAD

**Issue by JesseBowling** [CommunityHoneyNetwork/rdphoney#3]
When trying to start container with:

```docker-compose up```

This error:

```
rdphoney_1  | ./run: line 26: /etc/rdphoney/rdphoney.json: No such file or directory
```

**Comment by JesseBowling** [comment]
Setting docker-compose.yml like so:

```
        volumes:
            - ./rdphoney.sysconfig:/etc/rdphoney/rdphoney.json
```

Changes the error to:

```
rdphoney_1  | [CRIT] - No deploy key found
```

**Comment by JesseBowling** [comment]
Suspect the issue is here:

 rdphoney/rdphoney.run.j2 
```
RDPHONEY_JSON='/etc/rdphoney/rdphoney.json'
```

Unsure of architecture to suggest fix.

**Comment by amerck** [comment]
The documentation has been updated to resolve this typo. I also fixed an issue in the documentation where the JSON registration directory was not being defined as a volume.
